[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/checkout/*"
  to = "/checkout.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"