[build]
  functions = "netlify/functions"
  publish = "public"

# Serve the checkout page for /checkout/
[[redirects]]
  from = "/checkout/*"
  to = "/checkout.html"
  status = 200

# Handle API requests for bundle data
[[redirects]]
  from = "/api/bundles/*"
  to = "/.netlify/functions/getUrls"
  status = 200

# Serve all other HTML files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"