[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/checkout/:id"
  to = "/.netlify/functions/checkout/:id"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"